# Generated by Django 5.1 on 2024-08-18 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0002_answer_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='data_type',
            field=models.CharField(choices=[('choice', 'Choice'), ('text', 'Text'), ('number', 'Number'), ('date', 'Date'), ('boolean', 'Boolean')], max_length=50),
        ),
    ]
